add CNAME to `deploy` script
rakutentech/engineering-blog pull request #18
Opened 2021-07-26 01:34 UTC by NemoOudeis

see https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/managing-a-custom-domain-for-your-github-pages-site

2021-07-26 02:10 UTC, jcayzac requested changes

2021-07-26 02:10 UTC, jcayzac commented on deploy
> +cp CNAME public
Just put `CNAME` in `static/` instead!

2021-07-26 05:57 UTC, NemoOudeis commented on deploy
> +cp CNAME public
good point 😁

2021-07-26 05:59 UTC, NemoOudeis commented on deploy
> +cp CNAME public
done

2021-07-26 13:03 UTC, boazy approved these changes

2021-07-27 00:13 UTC, jcayzac approved these changes

2021-07-27 00:13 UTC, merged